-- ================================================
-- Descricao: Analise de contas a pagar
-- Modulo: Financeiro
-- Tabelas: TGFCAB, TGFPAR, TGFTOP
-- Nota: Baseado em compras com ATUALFIN = -1
-- ================================================

-- Compras que geram a pagar (mes atual)
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    T.ATUALFIN,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = -1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER, T.ATUALFIN
ORDER BY VLR_TOTAL DESC;

-- A pagar por fornecedor (top 30)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        COUNT(*) AS QTD_NOTAS,
        SUM(C.VLRNOTA) AS VLR_A_PAGAR
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
    WHERE T.ATUALFIN = -1
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -3)
    GROUP BY P.CODPARC, P.NOMEPARC
    ORDER BY VLR_A_PAGAR DESC
) WHERE ROWNUM <= 30;

-- Evolucao mensal a pagar
SELECT
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_A_PAGAR
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = -1
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(C.DTNEG, 'YYYY-MM');

-- A pagar por empresa
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_A_PAGAR
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = -1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY VLR_A_PAGAR DESC;

-- Comparativo receber x pagar
SELECT
    'A RECEBER' AS TIPO,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = 1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
UNION ALL
SELECT
    'A PAGAR' AS TIPO,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = -1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM');

-- Saldo (receber - pagar) por mes
SELECT
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) AS VLR_RECEBER,
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS VLR_PAGAR,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) -
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SALDO
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN IN (1, -1)
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(C.DTNEG, 'YYYY-MM');
