-- ================================================
-- Descricao: Analise de contas a receber
-- Modulo: Financeiro
-- Tabelas: TGFCAB, TGFPAR, TGFTOP
-- Nota: Baseado em vendas com ATUALFIN = 1
-- ================================================

-- Vendas que geram a receber (mes atual)
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    T.ATUALFIN,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = 1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER, T.ATUALFIN
ORDER BY VLR_TOTAL DESC;

-- A receber por cliente (top 30)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        P.LIMCRED,
        COUNT(*) AS QTD_NOTAS,
        SUM(C.VLRNOTA) AS VLR_A_RECEBER
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
    WHERE T.ATUALFIN = 1
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -3)
    GROUP BY P.CODPARC, P.NOMEPARC, P.LIMCRED
    ORDER BY VLR_A_RECEBER DESC
) WHERE ROWNUM <= 30;

-- Evolucao mensal a receber
SELECT
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_A_RECEBER
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = 1
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(C.DTNEG, 'YYYY-MM');

-- A receber por empresa
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_A_RECEBER
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = 1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY VLR_A_RECEBER DESC;

-- Clientes com limite de credito estourado
-- (vendas acima do limite cadastrado)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        P.LIMCRED AS LIMITE,
        SUM(C.VLRNOTA) AS VLR_VENDIDO,
        SUM(C.VLRNOTA) - NVL(P.LIMCRED, 0) AS EXCEDIDO
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
    WHERE T.ATUALFIN = 1
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -3)
      AND P.LIMCRED > 0
    GROUP BY P.CODPARC, P.NOMEPARC, P.LIMCRED
    HAVING SUM(C.VLRNOTA) > P.LIMCRED
    ORDER BY EXCEDIDO DESC
) WHERE ROWNUM <= 20;
