-- ================================================
-- Descricao: Analise de fluxo de caixa
-- Modulo: Financeiro
-- Tabelas: TGFCAB, TGFTOP, TSIEMP
-- Nota: Baseado em ATUALFIN (1=receber, -1=pagar)
-- ================================================

-- Fluxo de caixa diario (mes atual)
SELECT
    TRUNC(C.DTNEG) AS DATA,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) AS ENTRADAS,
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SAIDAS,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) -
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SALDO_DIA
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN IN (1, -1)
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY TRUNC(C.DTNEG)
ORDER BY TRUNC(C.DTNEG);

-- Fluxo de caixa acumulado (mes atual)
SELECT
    DATA,
    ENTRADAS,
    SAIDAS,
    SALDO_DIA,
    SUM(SALDO_DIA) OVER (ORDER BY DATA) AS SALDO_ACUMULADO
FROM (
    SELECT
        TRUNC(C.DTNEG) AS DATA,
        SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) AS ENTRADAS,
        SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SAIDAS,
        SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) -
        SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SALDO_DIA
    FROM TGFCAB C
    JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
    WHERE T.ATUALFIN IN (1, -1)
      AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
    GROUP BY TRUNC(C.DTNEG)
)
ORDER BY DATA;

-- Fluxo por empresa (mes atual)
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) AS ENTRADAS,
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SAIDAS,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) -
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SALDO
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN IN (1, -1)
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY SALDO DESC;

-- Fluxo mensal (ultimos 12 meses)
SELECT
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) AS ENTRADAS,
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SAIDAS,
    SUM(CASE WHEN T.ATUALFIN = 1 THEN C.VLRNOTA ELSE 0 END) -
    SUM(CASE WHEN T.ATUALFIN = -1 THEN C.VLRNOTA ELSE 0 END) AS SALDO
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN IN (1, -1)
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(C.DTNEG, 'YYYY-MM');

-- Detalhamento entradas por TOP
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL,
    ROUND(SUM(C.VLRNOTA) * 100.0 /
        (SELECT SUM(VLRNOTA) FROM TGFCAB C2
         JOIN TGFTOP T2 ON C2.CODTIPOPER = T2.CODTIPOPER AND C2.DHTIPOPER = T2.DHALTER
         WHERE T2.ATUALFIN = 1 AND C2.DTNEG >= TRUNC(SYSDATE, 'MM')), 2) AS PERC
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = 1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER
ORDER BY VLR_TOTAL DESC;

-- Detalhamento saidas por TOP
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL,
    ROUND(SUM(C.VLRNOTA) * 100.0 /
        (SELECT SUM(VLRNOTA) FROM TGFCAB C2
         JOIN TGFTOP T2 ON C2.CODTIPOPER = T2.CODTIPOPER AND C2.DHTIPOPER = T2.DHALTER
         WHERE T2.ATUALFIN = -1 AND C2.DTNEG >= TRUNC(SYSDATE, 'MM')), 2) AS PERC
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE T.ATUALFIN = -1
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER
ORDER BY VLR_TOTAL DESC;
