-- ================================================
-- Descricao: Faturamento por empresa/filial
-- Modulo: Vendas
-- Tabelas: TGFCAB, TSIEMP
-- ================================================

-- Faturamento por empresa (mes atual)
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL,
    ROUND(AVG(C.VLRNOTA), 2) AS TICKET_MEDIO,
    ROUND(SUM(C.VLRNOTA) * 100.0 /
        (SELECT SUM(VLRNOTA) FROM TGFCAB
         WHERE TIPMOV = 'V' AND CODTIPOPER IN (1100,1101)
         AND DTNEG >= TRUNC(SYSDATE, 'MM')), 2) AS PERC_TOTAL
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY VLR_TOTAL DESC;

-- Evolucao mensal por empresa
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
GROUP BY E.CODEMP, E.NOMEFANTASIA, TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY E.CODEMP, MES;

-- Comparativo filiais (mes atual vs anterior)
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    SUM(CASE WHEN C.DTNEG >= TRUNC(SYSDATE, 'MM') THEN C.VLRNOTA ELSE 0 END) AS VLR_MES_ATUAL,
    SUM(CASE WHEN C.DTNEG < TRUNC(SYSDATE, 'MM') THEN C.VLRNOTA ELSE 0 END) AS VLR_MES_ANTERIOR,
    ROUND(
        (SUM(CASE WHEN C.DTNEG >= TRUNC(SYSDATE, 'MM') THEN C.VLRNOTA ELSE 0 END) -
         SUM(CASE WHEN C.DTNEG < TRUNC(SYSDATE, 'MM') THEN C.VLRNOTA ELSE 0 END)) * 100.0 /
        NULLIF(SUM(CASE WHEN C.DTNEG < TRUNC(SYSDATE, 'MM') THEN C.VLRNOTA ELSE 0 END), 0)
    , 2) AS VARIACAO_PERC
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY VLR_MES_ATUAL DESC;

-- Faturamento por TOP e empresa
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    T.CODTIPOPER,
    T.DESCROPER,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.TIPMOV = 'V'
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA, T.CODTIPOPER, T.DESCROPER
ORDER BY E.CODEMP, VLR_TOTAL DESC;
