-- ================================================
-- Descricao: Notas por TOP (tipo de operacao)
-- Modulo: Vendas / Geral
-- Tabelas: TGFCAB, TGFTOP
-- ================================================

-- TOPs mais usadas (todas)
SELECT * FROM (
    SELECT
        T.CODTIPOPER,
        T.DESCROPER,
        T.TIPMOV,
        T.ATUALEST,
        T.ATUALFIN,
        T.NFE,
        COUNT(*) AS QTD_NOTAS,
        SUM(C.VLRNOTA) AS VLR_TOTAL,
        ROUND(AVG(C.VLRNOTA), 2) AS TICKET_MEDIO
    FROM TGFCAB C
    JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
    GROUP BY T.CODTIPOPER, T.DESCROPER, T.TIPMOV, T.ATUALEST, T.ATUALFIN, T.NFE
    ORDER BY QTD_NOTAS DESC
) WHERE ROWNUM <= 30;

-- TOPs de venda (mes atual)
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL,
    ROUND(SUM(C.VLRNOTA) * 100.0 /
        (SELECT SUM(VLRNOTA) FROM TGFCAB
         WHERE TIPMOV = 'V' AND DTNEG >= TRUNC(SYSDATE, 'MM')), 2) AS PERC_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.TIPMOV = 'V'
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER
ORDER BY VLR_TOTAL DESC;

-- TOPs de compra (mes atual)
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.TIPMOV = 'C'
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER
ORDER BY VLR_TOTAL DESC;

-- Distribuicao por TIPMOV
SELECT
    TIPMOV,
    CASE TIPMOV
        WHEN 'V' THEN 'Venda'
        WHEN 'C' THEN 'Compra'
        WHEN 'P' THEN 'Pedido'
        WHEN 'D' THEN 'Devolucao'
        WHEN 'O' THEN 'Pedido Compra'
        WHEN 'E' THEN 'Entrada'
        WHEN 'J' THEN 'Solicitacao'
        WHEN 'T' THEN 'Transferencia'
        ELSE 'Outros'
    END AS DESCRICAO,
    COUNT(*) AS QTD_NOTAS,
    SUM(VLRNOTA) AS VLR_TOTAL
FROM TGFCAB
WHERE DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY TIPMOV
ORDER BY QTD_NOTAS DESC;

-- TOPs que afetam estoque
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    T.TIPMOV,
    T.ATUALEST,
    CASE T.ATUALEST
        WHEN 'B' THEN 'Baixa (Saida)'
        WHEN 'E' THEN 'Entrada'
        WHEN 'R' THEN 'Reserva'
        WHEN 'N' THEN 'Nao Atualiza'
        ELSE 'Outros'
    END AS DESC_ATUALEST,
    COUNT(*) AS QTD_NOTAS
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND T.ATUALEST IN ('B', 'E', 'R')
GROUP BY T.CODTIPOPER, T.DESCROPER, T.TIPMOV, T.ATUALEST
ORDER BY QTD_NOTAS DESC;
