-- ================================================
-- Descricao: Vendas por vendedor
-- Modulo: Vendas
-- Tabelas: TGFCAB, TGFVEN
-- Nota: CODVEND=0 significa "sem vendedor"
-- ================================================

-- Ranking de vendedores (mes atual)
SELECT * FROM (
    SELECT
        V.CODVEND,
        V.APELIDO,
        V.TIPVEND,
        COUNT(*) AS QTD_VENDAS,
        SUM(C.VLRNOTA) AS VLR_TOTAL,
        ROUND(AVG(C.VLRNOTA), 2) AS TICKET_MEDIO,
        ROUND(SUM(C.VLRNOTA) * 100.0 /
            (SELECT SUM(VLRNOTA) FROM TGFCAB
             WHERE TIPMOV = 'V' AND CODTIPOPER IN (1100,1101)
             AND DTNEG >= TRUNC(SYSDATE, 'MM')), 2) AS PERC_TOTAL
    FROM TGFCAB C
    JOIN TGFVEN V ON C.CODVEND = V.CODVEND
    WHERE C.TIPMOV = 'V'
      AND C.CODTIPOPER IN (1100, 1101)
      AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
    GROUP BY V.CODVEND, V.APELIDO, V.TIPVEND
    ORDER BY VLR_TOTAL DESC
) WHERE ROWNUM <= 20;

-- Vendas sem vendedor vs com vendedor
SELECT
    CASE WHEN CODVEND = 0 THEN 'SEM VENDEDOR' ELSE 'COM VENDEDOR' END AS TIPO,
    COUNT(*) AS QTD_VENDAS,
    SUM(VLRNOTA) AS VLR_TOTAL,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM TGFCAB WHERE TIPMOV = 'V'), 2) AS PERC
FROM TGFCAB
WHERE TIPMOV = 'V'
  AND CODTIPOPER IN (1100, 1101)
GROUP BY CASE WHEN CODVEND = 0 THEN 'SEM VENDEDOR' ELSE 'COM VENDEDOR' END;

-- Vendas por vendedor e gerente
SELECT
    G.APELIDO AS GERENTE,
    V.CODVEND,
    V.APELIDO AS VENDEDOR,
    COUNT(*) AS QTD_VENDAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFVEN V ON C.CODVEND = V.CODVEND
LEFT JOIN TGFVEN G ON V.CODGER = G.CODVEND
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND V.CODVEND > 0
GROUP BY G.APELIDO, V.CODVEND, V.APELIDO
ORDER BY G.APELIDO NULLS LAST, VLR_TOTAL DESC;

-- Evolucao mensal por vendedor (top 5)
SELECT
    V.APELIDO,
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFVEN V ON C.CODVEND = V.CODVEND
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
  AND V.CODVEND IN (
      SELECT CODVEND FROM (
          SELECT CODVEND, SUM(VLRNOTA) AS VLR
          FROM TGFCAB
          WHERE TIPMOV = 'V' AND CODTIPOPER IN (1100,1101)
          GROUP BY CODVEND
          ORDER BY VLR DESC
      ) WHERE ROWNUM <= 5 AND CODVEND > 0
  )
GROUP BY V.APELIDO, TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY V.APELIDO, MES;
