-- ================================================
-- Descricao: Vendas por cliente (parceiro)
-- Modulo: Vendas
-- Tabelas: TGFCAB, TGFPAR
-- ================================================

-- Top 20 clientes (mes atual)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        P.TIPPESSOA,
        P.CLIENTE,
        COUNT(*) AS QTD_COMPRAS,
        SUM(C.VLRNOTA) AS VLR_TOTAL,
        ROUND(AVG(C.VLRNOTA), 2) AS TICKET_MEDIO,
        MAX(C.DTNEG) AS ULTIMA_COMPRA
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    WHERE C.TIPMOV = 'V'
      AND C.CODTIPOPER IN (1100, 1101)
      AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
    GROUP BY P.CODPARC, P.NOMEPARC, P.TIPPESSOA, P.CLIENTE
    ORDER BY VLR_TOTAL DESC
) WHERE ROWNUM <= 20;

-- Clientes por tipo (PF x PJ)
SELECT
    CASE P.TIPPESSOA
        WHEN 'J' THEN 'PESSOA JURIDICA'
        WHEN 'F' THEN 'PESSOA FISICA'
        ELSE 'OUTROS'
    END AS TIPO_PESSOA,
    COUNT(DISTINCT C.CODPARC) AS QTD_CLIENTES,
    COUNT(*) AS QTD_VENDAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFPAR P ON C.CODPARC = P.CODPARC
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY P.TIPPESSOA
ORDER BY VLR_TOTAL DESC;

-- Clientes novos (primeira compra no mes)
SELECT
    P.CODPARC,
    P.NOMEPARC,
    MIN(C.DTNEG) AS PRIMEIRA_COMPRA,
    COUNT(*) AS QTD_COMPRAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFPAR P ON C.CODPARC = P.CODPARC
WHERE C.TIPMOV = 'V'
  AND C.CODTIPOPER IN (1100, 1101)
  AND P.CODPARC NOT IN (
      SELECT DISTINCT CODPARC FROM TGFCAB
      WHERE TIPMOV = 'V' AND DTNEG < TRUNC(SYSDATE, 'MM')
  )
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY P.CODPARC, P.NOMEPARC
ORDER BY VLR_TOTAL DESC;

-- Clientes inativos (sem compra nos ultimos 90 dias)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        P.TELEFONE,
        P.EMAIL,
        MAX(C.DTNEG) AS ULTIMA_COMPRA,
        TRUNC(SYSDATE) - MAX(C.DTNEG) AS DIAS_INATIVO,
        COUNT(*) AS TOTAL_COMPRAS,
        SUM(C.VLRNOTA) AS VLR_HISTORICO
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    WHERE C.TIPMOV = 'V'
      AND C.CODTIPOPER IN (1100, 1101)
      AND P.CLIENTE = 'S'
    GROUP BY P.CODPARC, P.NOMEPARC, P.TELEFONE, P.EMAIL
    HAVING MAX(C.DTNEG) < SYSDATE - 90
    ORDER BY VLR_HISTORICO DESC
) WHERE ROWNUM <= 50;

-- Frequencia de compra por cliente (top clientes)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        COUNT(*) AS QTD_COMPRAS,
        MIN(C.DTNEG) AS PRIMEIRA_COMPRA,
        MAX(C.DTNEG) AS ULTIMA_COMPRA,
        ROUND((MAX(C.DTNEG) - MIN(C.DTNEG)) / NULLIF(COUNT(*) - 1, 0), 1) AS DIAS_ENTRE_COMPRAS,
        SUM(C.VLRNOTA) AS VLR_TOTAL
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    WHERE C.TIPMOV = 'V'
      AND C.CODTIPOPER IN (1100, 1101)
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -12)
    GROUP BY P.CODPARC, P.NOMEPARC
    HAVING COUNT(*) >= 5
    ORDER BY QTD_COMPRAS DESC
) WHERE ROWNUM <= 30;
