-- ================================================
-- Descricao: Compras por fornecedor
-- Modulo: Compras
-- Tabelas: TGFCAB, TGFPAR
-- ================================================

-- Top 20 fornecedores (mes atual)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        P.CGC_CPF,
        COUNT(*) AS QTD_COMPRAS,
        SUM(C.VLRNOTA) AS VLR_TOTAL,
        ROUND(AVG(C.VLRNOTA), 2) AS VALOR_MEDIO,
        MAX(C.DTNEG) AS ULTIMA_COMPRA
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    WHERE C.TIPMOV = 'C'
      AND C.CODTIPOPER = 1209
      AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
    GROUP BY P.CODPARC, P.NOMEPARC, P.CGC_CPF
    ORDER BY VLR_TOTAL DESC
) WHERE ROWNUM <= 20;

-- Top fornecedores historico (ultimos 12 meses)
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        COUNT(*) AS QTD_COMPRAS,
        SUM(C.VLRNOTA) AS VLR_TOTAL,
        ROUND(SUM(C.VLRNOTA) * 100.0 /
            (SELECT SUM(VLRNOTA) FROM TGFCAB
             WHERE TIPMOV = 'C' AND CODTIPOPER = 1209
             AND DTNEG >= ADD_MONTHS(SYSDATE, -12)), 2) AS PERC_TOTAL
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    WHERE C.TIPMOV = 'C'
      AND C.CODTIPOPER = 1209
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -12)
    GROUP BY P.CODPARC, P.NOMEPARC
    ORDER BY VLR_TOTAL DESC
) WHERE ROWNUM <= 30;

-- Evolucao compras por fornecedor (top 5)
SELECT
    P.NOMEPARC,
    TO_CHAR(C.DTNEG, 'YYYY-MM') AS MES,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFPAR P ON C.CODPARC = P.CODPARC
WHERE C.TIPMOV = 'C'
  AND C.CODTIPOPER = 1209
  AND C.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
  AND P.CODPARC IN (
      SELECT CODPARC FROM (
          SELECT CODPARC, SUM(VLRNOTA) AS VLR
          FROM TGFCAB
          WHERE TIPMOV = 'C' AND CODTIPOPER = 1209
          GROUP BY CODPARC
          ORDER BY VLR DESC
      ) WHERE ROWNUM <= 5
  )
GROUP BY P.NOMEPARC, TO_CHAR(C.DTNEG, 'YYYY-MM')
ORDER BY P.NOMEPARC, MES;

-- Fornecedores novos no periodo
SELECT
    P.CODPARC,
    P.NOMEPARC,
    MIN(C.DTNEG) AS PRIMEIRA_COMPRA,
    COUNT(*) AS QTD_COMPRAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFPAR P ON C.CODPARC = P.CODPARC
WHERE C.TIPMOV = 'C'
  AND C.CODTIPOPER = 1209
  AND P.CODPARC NOT IN (
      SELECT DISTINCT CODPARC FROM TGFCAB
      WHERE TIPMOV = 'C' AND DTNEG < TRUNC(SYSDATE, 'MM')
  )
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY P.CODPARC, P.NOMEPARC
ORDER BY VLR_TOTAL DESC;
