-- ================================================
-- Descricao: Compras por periodo
-- Modulo: Compras
-- Tabelas: TGFCAB, TGFTOP
-- TOP principal: 1209 (Compra mercadoria revenda)
-- ================================================

-- Compras do mes atual
SELECT
    COUNT(*) AS QTD_COMPRAS,
    SUM(VLRNOTA) AS VLR_TOTAL,
    ROUND(AVG(VLRNOTA), 2) AS VALOR_MEDIO
FROM TGFCAB
WHERE TIPMOV = 'C'
  AND CODTIPOPER = 1209
  AND DTNEG >= TRUNC(SYSDATE, 'MM');

-- Compras por dia (mes atual)
SELECT
    TRUNC(DTNEG) AS DATA,
    COUNT(*) AS QTD_COMPRAS,
    SUM(VLRNOTA) AS VLR_TOTAL
FROM TGFCAB
WHERE TIPMOV = 'C'
  AND CODTIPOPER = 1209
  AND DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY TRUNC(DTNEG)
ORDER BY TRUNC(DTNEG);

-- Compras ultimos 12 meses
SELECT
    TO_CHAR(DTNEG, 'YYYY-MM') AS MES,
    COUNT(*) AS QTD_COMPRAS,
    SUM(VLRNOTA) AS VLR_TOTAL
FROM TGFCAB
WHERE TIPMOV = 'C'
  AND CODTIPOPER = 1209
  AND DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(DTNEG, 'YYYY-MM');

-- Compras por TOP
SELECT
    T.CODTIPOPER,
    T.DESCROPER,
    COUNT(*) AS QTD_COMPRAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.TIPMOV = 'C'
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY T.CODTIPOPER, T.DESCROPER
ORDER BY VLR_TOTAL DESC;
