-- ================================================
-- Descricao: Pedidos de compra pendentes
-- Modulo: Compras
-- Tabelas: TGFCAB, TGFPAR, TGFVEN
-- TOPs: 1301 (Pedido compra), 1804 (Solicitacao)
-- ================================================

-- Pedidos de compra pendentes
SELECT
    C.NUNOTA,
    C.DTNEG,
    P.NOMEPARC AS FORNECEDOR,
    V.APELIDO AS COMPRADOR,
    C.VLRNOTA,
    TRUNC(SYSDATE) - TRUNC(C.DTNEG) AS DIAS_ABERTO,
    C.STATUSNOTA
FROM TGFCAB C
JOIN TGFPAR P ON C.CODPARC = P.CODPARC
LEFT JOIN TGFVEN V ON C.CODVEND = V.CODVEND
WHERE C.TIPMOV = 'O'
  AND C.CODTIPOPER = 1301
  AND C.STATUSNOTA <> 'L'
ORDER BY C.DTNEG;

-- Solicitacoes de compra abertas
SELECT
    C.NUNOTA,
    C.DTNEG,
    C.VLRNOTA,
    TRUNC(SYSDATE) - TRUNC(C.DTNEG) AS DIAS_ABERTO,
    C.STATUSNOTA
FROM TGFCAB C
WHERE C.TIPMOV = 'J'
  AND C.CODTIPOPER = 1804
  AND C.STATUSNOTA <> 'L'
ORDER BY C.DTNEG;

-- Resumo pedidos por status
SELECT
    STATUSNOTA,
    CASE STATUSNOTA
        WHEN 'L' THEN 'Liberado'
        WHEN 'P' THEN 'Pendente'
        WHEN 'A' THEN 'Aberto'
        ELSE STATUSNOTA
    END AS DESC_STATUS,
    COUNT(*) AS QTD,
    SUM(VLRNOTA) AS VLR_TOTAL
FROM TGFCAB
WHERE TIPMOV = 'O'
  AND CODTIPOPER = 1301
  AND DTNEG >= ADD_MONTHS(SYSDATE, -3)
GROUP BY STATUSNOTA
ORDER BY QTD DESC;

-- Pedidos antigos (mais de 30 dias)
SELECT
    C.NUNOTA,
    C.DTNEG,
    P.NOMEPARC AS FORNECEDOR,
    C.VLRNOTA,
    TRUNC(SYSDATE) - TRUNC(C.DTNEG) AS DIAS_ABERTO
FROM TGFCAB C
JOIN TGFPAR P ON C.CODPARC = P.CODPARC
WHERE C.TIPMOV = 'O'
  AND C.CODTIPOPER = 1301
  AND C.STATUSNOTA <> 'L'
  AND C.DTNEG < SYSDATE - 30
ORDER BY C.DTNEG;

-- Valor total pendente por comprador
SELECT
    V.CODVEND,
    V.APELIDO AS COMPRADOR,
    COUNT(*) AS QTD_PEDIDOS,
    SUM(C.VLRNOTA) AS VLR_PENDENTE
FROM TGFCAB C
JOIN TGFVEN V ON C.CODVEND = V.CODVEND
WHERE C.TIPMOV = 'O'
  AND C.CODTIPOPER = 1301
  AND C.STATUSNOTA <> 'L'
GROUP BY V.CODVEND, V.APELIDO
ORDER BY VLR_PENDENTE DESC;
