-- ================================================
-- Descricao: Pedidos de compra pendentes (com entregas parciais)
-- Modulo: Compras
-- Tabelas: TGFCAB, TGFITE, TGFPRO, TGFMAR, TGFVAR, TGFPAR, TGFVEN, TSIEMP
-- TOPs: 1301 (Compra Estoque), 1313 (Compra Casada/Entrega Futura)
-- Baseado nos exemplos 22-23 da base de conhecimento
-- ================================================

-- ================================================
-- 1. Pedidos de compra pendentes - RESUMO POR PEDIDO
--    Calcula valor REAL pendente descontando entregas parciais (TGFVAR)
-- ================================================
SELECT
    CAB.NUNOTA AS PEDIDO,
    TO_CHAR(CAB.DTNEG, 'DD/MM/YYYY') AS DT_PEDIDO,
    PAR.NOMEPARC AS FORNECEDOR,
    VEN.APELIDO AS COMPRADOR,
    COUNT(DISTINCT ITE.SEQUENCIA) AS QTD_ITENS,
    SUM(ITE.QTDNEG) AS QTD_TOTAL_PEDIDA,
    SUM(NVL(V_AGG.TOTAL_ATENDIDO, 0)) AS QTD_TOTAL_ENTREGUE,
    SUM(ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) AS QTD_TOTAL_PENDENTE,
    SUM(ITE.VLRTOT) AS VLR_TOTAL_PEDIDO,
    SUM(ROUND(NVL(V_AGG.TOTAL_ATENDIDO, 0) * ITE.VLRUNIT, 2)) AS VLR_TOTAL_ATENDIDO,
    SUM(ROUND((ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) * ITE.VLRUNIT, 2)) AS VLR_TOTAL_PENDENTE,
    NVL(TO_CHAR(CAB.DTPREVENT, 'DD/MM/YYYY'), 'Sem previsao') AS PREVISAO_ENTREGA,
    TRUNC(SYSDATE) - TRUNC(CAB.DTNEG) AS DIAS_ABERTO,
    CAB.STATUSNOTA
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN (
    SELECT V.NUNOTAORIG, V.SEQUENCIAORIG,
           SUM(V.QTDATENDIDA) AS TOTAL_ATENDIDO
    FROM TGFVAR V
    JOIN TGFCAB C ON C.NUNOTA = V.NUNOTA
    WHERE C.STATUSNOTA <> 'C'
    GROUP BY V.NUNOTAORIG, V.SEQUENCIAORIG
) V_AGG ON V_AGG.NUNOTAORIG = ITE.NUNOTA
       AND V_AGG.SEQUENCIAORIG = ITE.SEQUENCIA
WHERE CAB.CODTIPOPER IN (1301, 1313)
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA <> 'C'
  AND ITE.PENDENTE = 'S'
  AND (ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) > 0
GROUP BY CAB.NUNOTA, CAB.DTNEG, PAR.NOMEPARC, VEN.APELIDO,
         CAB.DTPREVENT, CAB.STATUSNOTA
ORDER BY DIAS_ABERTO DESC;

-- ================================================
-- 2. Solicitacoes de compra abertas
-- ================================================
SELECT
    CAB.NUNOTA AS SOLICITACAO,
    TO_CHAR(CAB.DTNEG, 'DD/MM/YYYY') AS DT_SOLICITACAO,
    SUM(ITE.VLRTOT) AS VLR_TOTAL,
    COUNT(DISTINCT ITE.SEQUENCIA) AS QTD_ITENS,
    TRUNC(SYSDATE) - TRUNC(CAB.DTNEG) AS DIAS_ABERTO,
    CAB.STATUSNOTA
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.TIPMOV = 'J'
  AND CAB.CODTIPOPER = 1804
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA <> 'C'
GROUP BY CAB.NUNOTA, CAB.DTNEG, CAB.STATUSNOTA
ORDER BY CAB.DTNEG;

-- ================================================
-- 3. Resumo pedidos pendentes por status
-- ================================================
SELECT
    CAB.STATUSNOTA,
    CASE CAB.STATUSNOTA
        WHEN 'L' THEN 'Liberado'
        WHEN 'P' THEN 'Pendente'
        WHEN 'A' THEN 'Atendimento'
        ELSE CAB.STATUSNOTA
    END AS DESC_STATUS,
    COUNT(DISTINCT CAB.NUNOTA) AS QTD_PEDIDOS,
    SUM(ROUND((ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) * ITE.VLRUNIT, 2)) AS VLR_PENDENTE
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN (
    SELECT V.NUNOTAORIG, V.SEQUENCIAORIG,
           SUM(V.QTDATENDIDA) AS TOTAL_ATENDIDO
    FROM TGFVAR V
    JOIN TGFCAB C ON C.NUNOTA = V.NUNOTA
    WHERE C.STATUSNOTA <> 'C'
    GROUP BY V.NUNOTAORIG, V.SEQUENCIAORIG
) V_AGG ON V_AGG.NUNOTAORIG = ITE.NUNOTA
       AND V_AGG.SEQUENCIAORIG = ITE.SEQUENCIA
WHERE CAB.CODTIPOPER IN (1301, 1313)
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA <> 'C'
  AND ITE.PENDENTE = 'S'
  AND (ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) > 0
GROUP BY CAB.STATUSNOTA
ORDER BY QTD_PEDIDOS DESC;

-- ================================================
-- 4. Pedidos atrasados (previsao de entrega ultrapassada)
-- ================================================
SELECT
    CAB.NUNOTA AS PEDIDO,
    TO_CHAR(CAB.DTNEG, 'DD/MM/YYYY') AS DT_PEDIDO,
    TO_CHAR(CAB.DTPREVENT, 'DD/MM/YYYY') AS PREVISAO_ENTREGA,
    TRUNC(SYSDATE) - TRUNC(CAB.DTPREVENT) AS DIAS_ATRASADO,
    PAR.NOMEPARC AS FORNECEDOR,
    VEN.APELIDO AS COMPRADOR,
    SUM(ROUND((ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) * ITE.VLRUNIT, 2)) AS VLR_PENDENTE
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN (
    SELECT V.NUNOTAORIG, V.SEQUENCIAORIG,
           SUM(V.QTDATENDIDA) AS TOTAL_ATENDIDO
    FROM TGFVAR V
    JOIN TGFCAB C ON C.NUNOTA = V.NUNOTA
    WHERE C.STATUSNOTA <> 'C'
    GROUP BY V.NUNOTAORIG, V.SEQUENCIAORIG
) V_AGG ON V_AGG.NUNOTAORIG = ITE.NUNOTA
       AND V_AGG.SEQUENCIAORIG = ITE.SEQUENCIA
WHERE CAB.CODTIPOPER IN (1301, 1313)
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA <> 'C'
  AND ITE.PENDENTE = 'S'
  AND (ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) > 0
  AND CAB.DTPREVENT IS NOT NULL
  AND CAB.DTPREVENT < TRUNC(SYSDATE)
GROUP BY CAB.NUNOTA, CAB.DTNEG, CAB.DTPREVENT,
         PAR.NOMEPARC, VEN.APELIDO
ORDER BY DIAS_ATRASADO DESC;

-- ================================================
-- 5. Valor pendente REAL por comprador
--    Usa TGFVAR para descontar entregas parciais
-- ================================================
SELECT
    VEN.CODVEND,
    VEN.APELIDO AS COMPRADOR,
    COUNT(DISTINCT CAB.NUNOTA) AS QTD_PEDIDOS,
    SUM(ITE.VLRTOT) AS VLR_TOTAL_PEDIDO,
    SUM(ROUND(NVL(V_AGG.TOTAL_ATENDIDO, 0) * ITE.VLRUNIT, 2)) AS VLR_TOTAL_ATENDIDO,
    SUM(ROUND((ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) * ITE.VLRUNIT, 2)) AS VLR_TOTAL_PENDENTE
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN (
    SELECT V.NUNOTAORIG, V.SEQUENCIAORIG,
           SUM(V.QTDATENDIDA) AS TOTAL_ATENDIDO
    FROM TGFVAR V
    JOIN TGFCAB C ON C.NUNOTA = V.NUNOTA
    WHERE C.STATUSNOTA <> 'C'
    GROUP BY V.NUNOTAORIG, V.SEQUENCIAORIG
) V_AGG ON V_AGG.NUNOTAORIG = ITE.NUNOTA
       AND V_AGG.SEQUENCIAORIG = ITE.SEQUENCIA
WHERE CAB.CODTIPOPER IN (1301, 1313)
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA <> 'C'
  AND ITE.PENDENTE = 'S'
  AND (ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) > 0
GROUP BY VEN.CODVEND, VEN.APELIDO
ORDER BY VLR_TOTAL_PENDENTE DESC;
