-- ================================================
-- Descricao: Analise de devolucoes
-- Modulo: Estoque / Vendas
-- Tabelas: TGFCAB, TGFITE, TGFPAR, TGFPRO
-- TOPs: 1202 (Dev. venda), 1501 (Dev. compra)
-- ================================================

-- Resumo devolucoes (mes atual)
SELECT
    CASE
        WHEN CODTIPOPER = 1202 THEN 'DEVOLUCAO VENDA'
        WHEN CODTIPOPER = 1501 THEN 'DEVOLUCAO COMPRA'
        ELSE 'OUTRAS'
    END AS TIPO,
    COUNT(*) AS QTD_DEVOLUCOES,
    SUM(VLRNOTA) AS VLR_TOTAL
FROM TGFCAB
WHERE CODTIPOPER IN (1202, 1501)
  AND DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY
    CASE
        WHEN CODTIPOPER = 1202 THEN 'DEVOLUCAO VENDA'
        WHEN CODTIPOPER = 1501 THEN 'DEVOLUCAO COMPRA'
        ELSE 'OUTRAS'
    END;

-- Taxa de devolucao de vendas
SELECT
    ROUND(
        (SELECT COUNT(*) FROM TGFCAB
         WHERE CODTIPOPER = 1202
         AND DTNEG >= TRUNC(SYSDATE, 'MM')) * 100.0 /
        NULLIF((SELECT COUNT(*) FROM TGFCAB
         WHERE CODTIPOPER IN (1100, 1101)
         AND DTNEG >= TRUNC(SYSDATE, 'MM')), 0)
    , 2) AS TAXA_DEVOLUCAO_QTD,
    ROUND(
        (SELECT SUM(VLRNOTA) FROM TGFCAB
         WHERE CODTIPOPER = 1202
         AND DTNEG >= TRUNC(SYSDATE, 'MM')) * 100.0 /
        NULLIF((SELECT SUM(VLRNOTA) FROM TGFCAB
         WHERE CODTIPOPER IN (1100, 1101)
         AND DTNEG >= TRUNC(SYSDATE, 'MM')), 0)
    , 2) AS TAXA_DEVOLUCAO_VLR
FROM DUAL;

-- Devolucoes de venda por cliente
SELECT * FROM (
    SELECT
        P.CODPARC,
        P.NOMEPARC,
        COUNT(*) AS QTD_DEVOLUCOES,
        SUM(C.VLRNOTA) AS VLR_DEVOLVIDO
    FROM TGFCAB C
    JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    WHERE C.CODTIPOPER = 1202
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -3)
    GROUP BY P.CODPARC, P.NOMEPARC
    ORDER BY QTD_DEVOLUCOES DESC
) WHERE ROWNUM <= 20;

-- Produtos mais devolvidos
SELECT * FROM (
    SELECT
        P.CODPROD,
        P.DESCRPROD,
        P.MARCA,
        COUNT(DISTINCT C.NUNOTA) AS QTD_NOTAS_DEV,
        SUM(I.QTDNEG) AS QTD_ITENS_DEV,
        SUM(I.VLRTOT) AS VLR_DEVOLVIDO
    FROM TGFITE I
    JOIN TGFCAB C ON I.NUNOTA = C.NUNOTA
    JOIN TGFPRO P ON I.CODPROD = P.CODPROD
    WHERE C.CODTIPOPER = 1202
      AND C.DTNEG >= ADD_MONTHS(SYSDATE, -3)
    GROUP BY P.CODPROD, P.DESCRPROD, P.MARCA
    ORDER BY QTD_NOTAS_DEV DESC
) WHERE ROWNUM <= 30;

-- Evolucao mensal devolucoes
SELECT
    TO_CHAR(DTNEG, 'YYYY-MM') AS MES,
    SUM(CASE WHEN CODTIPOPER = 1202 THEN 1 ELSE 0 END) AS QTD_DEV_VENDA,
    SUM(CASE WHEN CODTIPOPER = 1202 THEN VLRNOTA ELSE 0 END) AS VLR_DEV_VENDA,
    SUM(CASE WHEN CODTIPOPER = 1501 THEN 1 ELSE 0 END) AS QTD_DEV_COMPRA,
    SUM(CASE WHEN CODTIPOPER = 1501 THEN VLRNOTA ELSE 0 END) AS VLR_DEV_COMPRA
FROM TGFCAB
WHERE CODTIPOPER IN (1202, 1501)
  AND DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(DTNEG, 'YYYY-MM');

-- Devolucoes por empresa
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    SUM(CASE WHEN C.CODTIPOPER = 1202 THEN 1 ELSE 0 END) AS QTD_DEV_VENDA,
    SUM(CASE WHEN C.CODTIPOPER = 1202 THEN C.VLRNOTA ELSE 0 END) AS VLR_DEV_VENDA,
    SUM(CASE WHEN C.CODTIPOPER = 1501 THEN 1 ELSE 0 END) AS QTD_DEV_COMPRA,
    SUM(CASE WHEN C.CODTIPOPER = 1501 THEN C.VLRNOTA ELSE 0 END) AS VLR_DEV_COMPRA
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
WHERE C.CODTIPOPER IN (1202, 1501)
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY E.CODEMP;
