-- ================================================
-- Descricao: Movimentacao de estoque
-- Modulo: Estoque
-- Tabelas: TGFCAB, TGFITE, TGFPRO, TGFTOP
-- ================================================

-- Movimentacoes por tipo (mes atual)
SELECT
    T.ATUALEST,
    CASE T.ATUALEST
        WHEN 'B' THEN 'Baixa (Saida)'
        WHEN 'E' THEN 'Entrada'
        WHEN 'R' THEN 'Reserva'
        WHEN 'N' THEN 'Nao Atualiza'
        ELSE 'Outros'
    END AS DESC_TIPO,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND T.ATUALEST IS NOT NULL
GROUP BY T.ATUALEST
ORDER BY QTD_NOTAS DESC;

-- Entradas vs Saidas de estoque (mes atual)
SELECT
    'ENTRADAS' AS TIPO,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND T.ATUALEST = 'E'
UNION ALL
SELECT
    'SAIDAS' AS TIPO,
    COUNT(*) AS QTD_NOTAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND T.ATUALEST = 'B';

-- Produtos com maior movimentacao (saida)
SELECT * FROM (
    SELECT
        P.CODPROD,
        P.DESCRPROD,
        P.MARCA,
        SUM(I.QTDNEG) AS QTD_SAIDA,
        COUNT(DISTINCT C.NUNOTA) AS QTD_NOTAS
    FROM TGFITE I
    JOIN TGFCAB C ON I.NUNOTA = C.NUNOTA
    JOIN TGFPRO P ON I.CODPROD = P.CODPROD
    JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
    WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
      AND T.ATUALEST = 'B'
    GROUP BY P.CODPROD, P.DESCRPROD, P.MARCA
    ORDER BY QTD_SAIDA DESC
) WHERE ROWNUM <= 50;

-- Movimentacao por empresa
SELECT
    E.CODEMP,
    E.NOMEFANTASIA,
    SUM(CASE WHEN T.ATUALEST = 'E' THEN 1 ELSE 0 END) AS QTD_ENTRADAS,
    SUM(CASE WHEN T.ATUALEST = 'E' THEN C.VLRNOTA ELSE 0 END) AS VLR_ENTRADAS,
    SUM(CASE WHEN T.ATUALEST = 'B' THEN 1 ELSE 0 END) AS QTD_SAIDAS,
    SUM(CASE WHEN T.ATUALEST = 'B' THEN C.VLRNOTA ELSE 0 END) AS VLR_SAIDAS
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND T.ATUALEST IN ('E', 'B')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY E.CODEMP;

-- Evolucao diaria entrada x saida
SELECT
    TRUNC(C.DTNEG) AS DATA,
    SUM(CASE WHEN T.ATUALEST = 'E' THEN C.VLRNOTA ELSE 0 END) AS VLR_ENTRADAS,
    SUM(CASE WHEN T.ATUALEST = 'B' THEN C.VLRNOTA ELSE 0 END) AS VLR_SAIDAS,
    SUM(CASE WHEN T.ATUALEST = 'E' THEN C.VLRNOTA ELSE 0 END) -
    SUM(CASE WHEN T.ATUALEST = 'B' THEN C.VLRNOTA ELSE 0 END) AS SALDO
FROM TGFCAB C
JOIN TGFTOP T ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE C.DTNEG >= TRUNC(SYSDATE, 'MM')
  AND T.ATUALEST IN ('E', 'B')
GROUP BY TRUNC(C.DTNEG)
ORDER BY TRUNC(C.DTNEG);
