-- ================================================
-- Descricao: Transferencias entre filiais
-- Modulo: Estoque
-- Tabelas: TGFCAB, TSIEMP, TGFPAR
-- TOPs: 1150 (Saida), 1452 (Entrada)
-- ================================================

-- Resumo transferencias (mes atual)
SELECT
    CASE CODTIPOPER
        WHEN 1150 THEN 'TRANSFERENCIA SAIDA'
        WHEN 1452 THEN 'TRANSFERENCIA ENTRADA'
    END AS TIPO,
    COUNT(*) AS QTD_NOTAS,
    SUM(VLRNOTA) AS VLR_TOTAL
FROM TGFCAB
WHERE CODTIPOPER IN (1150, 1452)
  AND DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY CODTIPOPER
ORDER BY CODTIPOPER;

-- Transferencias saida por origem
SELECT
    E.CODEMP,
    E.NOMEFANTASIA AS ORIGEM,
    COUNT(*) AS QTD_SAIDAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
WHERE C.CODTIPOPER = 1150
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY VLR_TOTAL DESC;

-- Transferencias entrada por destino
SELECT
    E.CODEMP,
    E.NOMEFANTASIA AS DESTINO,
    COUNT(*) AS QTD_ENTRADAS,
    SUM(C.VLRNOTA) AS VLR_TOTAL
FROM TGFCAB C
JOIN TSIEMP E ON C.CODEMP = E.CODEMP
WHERE C.CODTIPOPER = 1452
  AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
GROUP BY E.CODEMP, E.NOMEFANTASIA
ORDER BY VLR_TOTAL DESC;

-- Diferenca saida x entrada (possiveis em transito)
SELECT
    (SELECT COUNT(*) FROM TGFCAB WHERE CODTIPOPER = 1150
     AND DTNEG >= TRUNC(SYSDATE, 'MM')) AS QTD_SAIDAS,
    (SELECT COUNT(*) FROM TGFCAB WHERE CODTIPOPER = 1452
     AND DTNEG >= TRUNC(SYSDATE, 'MM')) AS QTD_ENTRADAS,
    (SELECT COUNT(*) FROM TGFCAB WHERE CODTIPOPER = 1150
     AND DTNEG >= TRUNC(SYSDATE, 'MM')) -
    (SELECT COUNT(*) FROM TGFCAB WHERE CODTIPOPER = 1452
     AND DTNEG >= TRUNC(SYSDATE, 'MM')) AS DIFERENCA_EM_TRANSITO,
    (SELECT SUM(VLRNOTA) FROM TGFCAB WHERE CODTIPOPER = 1150
     AND DTNEG >= TRUNC(SYSDATE, 'MM')) AS VLR_SAIDAS,
    (SELECT SUM(VLRNOTA) FROM TGFCAB WHERE CODTIPOPER = 1452
     AND DTNEG >= TRUNC(SYSDATE, 'MM')) AS VLR_ENTRADAS
FROM DUAL;

-- Transferencias recentes (ultimas 50)
SELECT * FROM (
    SELECT
        C.NUNOTA,
        C.DTNEG,
        CASE C.CODTIPOPER
            WHEN 1150 THEN 'SAIDA'
            WHEN 1452 THEN 'ENTRADA'
        END AS TIPO,
        E.NOMEFANTASIA AS EMPRESA,
        C.VLRNOTA
    FROM TGFCAB C
    JOIN TSIEMP E ON C.CODEMP = E.CODEMP
    WHERE C.CODTIPOPER IN (1150, 1452)
    ORDER BY C.DTNEG DESC
) WHERE ROWNUM <= 50;

-- Evolucao mensal transferencias
SELECT
    TO_CHAR(DTNEG, 'YYYY-MM') AS MES,
    SUM(CASE WHEN CODTIPOPER = 1150 THEN 1 ELSE 0 END) AS QTD_SAIDAS,
    SUM(CASE WHEN CODTIPOPER = 1150 THEN VLRNOTA ELSE 0 END) AS VLR_SAIDAS,
    SUM(CASE WHEN CODTIPOPER = 1452 THEN 1 ELSE 0 END) AS QTD_ENTRADAS,
    SUM(CASE WHEN CODTIPOPER = 1452 THEN VLRNOTA ELSE 0 END) AS VLR_ENTRADAS
FROM TGFCAB
WHERE CODTIPOPER IN (1150, 1452)
  AND DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12)
GROUP BY TO_CHAR(DTNEG, 'YYYY-MM')
ORDER BY TO_CHAR(DTNEG, 'YYYY-MM');

-- Produtos mais transferidos
SELECT * FROM (
    SELECT
        P.CODPROD,
        P.DESCRPROD,
        P.MARCA,
        COUNT(DISTINCT C.NUNOTA) AS QTD_TRANSF,
        SUM(I.QTDNEG) AS QTD_ITENS
    FROM TGFITE I
    JOIN TGFCAB C ON I.NUNOTA = C.NUNOTA
    JOIN TGFPRO P ON I.CODPROD = P.CODPROD
    WHERE C.CODTIPOPER = 1150
      AND C.DTNEG >= TRUNC(SYSDATE, 'MM')
    GROUP BY P.CODPROD, P.DESCRPROD, P.MARCA
    ORDER BY QTD_TRANSF DESC
) WHERE ROWNUM <= 30;
